# A generic, single-database configuration.

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration files
# file_template = %%(rev)s_%%(slug)s

# timezone to use when rendering the date within the migration file as
# well as the filename.
# string value is passed to dateutil.tz.gettz()
# leave blank for local time
# timezone =

# max length of characters to use for "slug" estate
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow scientists to compile/execute
# scripts without checking the DB connection
# output_encoding = utf-8

sqlalchemy.url = postgresql://postgres:postgres@db:5432/opener_dev


[post_write_hooks]
# post_write_hooks defines scripts or Python functions that are run
# on newly generated revision scripts.  See the documentation for details.

# format using "black" - run the command "black [filename]" after writing
# hooks = black
# black.type = console_scripts
# black.entrypoint = black
# black.options = -l 100

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = INFO
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
