"""add_price_image_spotify_fields

Revision ID: b4aea5d8a7ed
Revises: 20260621000003
Create Date: 2026-06-22 03:40:12.491670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4aea5d8a7ed'
down_revision: Union[str, None] = '20260621000003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artist_tags_artist_id'), table_name='artist_tags')
    op.add_column('artists', sa.Column('spotify_url', sa.String(length=500), nullable=True))
    op.add_column('artists', sa.Column('image_url', sa.Text(), nullable=True))
    op.add_column('artists', sa.Column('album_name', sa.String(length=500), nullable=True))
    op.add_column('artists', sa.Column('album_image_url', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_artists_mbid'), table_name='artists')
    op.drop_index(op.f('ix_event_snapshots_source'), table_name='event_snapshots')
    op.add_column('events', sa.Column('price', sa.String(length=100), nullable=True))
    op.add_column('events', sa.Column('image_url', sa.Text(), nullable=True))
    op.drop_index(op.f('ix_events_date'), table_name='events')
    op.drop_index(op.f('ix_events_source'), table_name='events')
    op.drop_index(op.f('ix_scrobbles_artist_name'), table_name='scrobbles')
    op.drop_index(op.f('ix_scrobbles_scrobbled_at'), table_name='scrobbles')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_scrobbles_scrobbled_at'), 'scrobbles', ['scrobbled_at'], unique=False)
    op.create_index(op.f('ix_scrobbles_artist_name'), 'scrobbles', ['artist_name'], unique=False)
    op.create_index(op.f('ix_events_source'), 'events', ['source'], unique=False)
    op.create_index(op.f('ix_events_date'), 'events', ['date'], unique=False)
    op.drop_column('events', 'image_url')
    op.drop_column('events', 'price')
    op.create_index(op.f('ix_event_snapshots_source'), 'event_snapshots', ['source'], unique=False)
    op.create_index(op.f('ix_artists_mbid'), 'artists', ['mbid'], unique=False)
    op.drop_column('artists', 'album_image_url')
    op.drop_column('artists', 'album_name')
    op.drop_column('artists', 'image_url')
    op.drop_column('artists', 'spotify_url')
    op.create_index(op.f('ix_artist_tags_artist_id'), 'artist_tags', ['artist_id'], unique=False)
    # ### end Alembic commands ###
