"""add_sold_out_to_events

Revision ID: bc9324610a89
Revises: b4aea5d8a7ed
Create Date: 2026-06-22 06:00:00.723150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc9324610a89'
down_revision: Union[str, None] = 'b4aea5d8a7ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('sold_out', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'sold_out')
    # ### end Alembic commands ###
